---
title: "AssignmentB2AS"
author: "Andras Szeitz"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
options(repos = c(CRAN = "https://cran.rstudio.com"))
```


```{r}
install.packages("devtools")
```


```{r}
install.packages("usethis")
```

Load a couple of packages

```{r}
library(devtools)
library(usethis)
```


```{r}
devtools::install_github("stat545ubc-2023/AssignmentB2AS", force = TRUE)
```

Load more packages

```{r}

#loading libraries 
library(datateachr)
library(tidyverse)
library(ggplot2)
library(testthat)
library(rlang)
library(lifecycle)
library(utf8)
library(fansi)

```

# Make a scatter plot


```{r}

#I wrote a function using the cancer_sample dataset from mda deliverable 1 to generate a scatter plot.

library(datateachr)
library(ggplot2)
scatter_plot <- function(x, y, x_label = "X-axis", y_label = "Y-axis", title = "Scatter Plot") {
  plot_data <- data.frame(x = x, y = y)
  
  # Suppressing warnings while creating the plot
  suppressWarnings({
    scatter_plot <- ggplot(plot_data, aes(x = x, y = y)) +
      geom_point(size = 1, color = "purple") +
      labs(x = x_label, y = y_label, title = title)
  })
  
  # Printing the scatter plot
  print(scatter_plot)
}

# Your scatter plot code here
scatter_plot(x = cancer_sample$concavity_mean, y = cancer_sample$smoothness_mean)

```


